# Generated by Django 3.0 on 2022-06-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220625_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
